version: '3.1'

env_file: .env

services:
  react-app-nginx:
    container_name: ${NAME:-react_app}
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${NGINX_CONF_FILE:-nginx.conf}:/etc/nginx/conf.d/default.conf
      - ./${DH_PARAM_PATH:-dh-param}/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ${LETSENCRYPT_PATH}/letsencrytp/live/${API_PATH}/fullchain.pem:/etc/letsencrypt/live/${API_PATH}/fullchain.pem
      - ${LETSENCRYPT_PATH}/letsencrypt/live/${API_PATH}/privkey.pem:/etc/letsencrypt/live/${API_PATH}/privkey.pem